using System.ComponentModel.DataAnnotations;

namespace CatalogueApp.Components.Models
{
    /// <summary>
    /// Represents an academic assignment in the Blazor client application.
    /// Used for creating, displaying, and managing assignment information.
    /// </summary>
    /// <remarks>
    /// This model includes validation attributes for form handling and data integrity.
    /// Maps to server-side assignment data structures.
    /// </remarks>
    public class AssignmentModel
    {
        /// <summary>
        /// Gets or sets the unique identifier for the assignment.
        /// </summary>
        /// <remarks>
        /// Auto-generated by the server when the assignment is created.
        /// Used for update and delete operations.
        /// </remarks>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the assignment.
        /// </summary>
        /// <remarks>
        /// Required field that describes the assignment's main topic or purpose.
        /// Displayed in assignment lists and detail views.
        /// </remarks>
        [Required]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the detailed description of the assignment.
        /// </summary>
        /// <remarks>
        /// Optional field that provides additional information about the assignment.
        /// Can include requirements, guidelines, or other relevant details.
        /// </remarks>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the name of the class this assignment belongs to.
        /// </summary>
        /// <remarks>
        /// Required field used to associate the assignment with a specific class.
        /// Used for filtering and organizing assignments by class.
        /// </remarks>
        [Required]
        public string ClassName { get; set; }

        /// <summary>
        /// Gets or sets the due date and time for the assignment.
        /// </summary>
        /// <remarks>
        /// Represents when the assignment must be completed.
        /// Used for sorting assignments and displaying deadlines.
        /// </remarks>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// Gets or sets the maximum points possible for the assignment.
        /// </summary>
        /// <remarks>
        /// Required field that defines the assignment's weight or value.
        /// Used for grade calculations and displaying potential scores.
        /// Must be a positive integer.
        /// </remarks>
        [Required]
        public int MaxPoints { get; set; }
    }
}